version: '3.8'

services: 
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1207
      POSTGRES_DB: zipredir
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
   
  backend:
    build:
      context: ./ZipRedir_backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/zipredir
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1207
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./zipredir_frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend


volumes:
  db_data: